<?php

namespace MainBundle\Repository;

/**
 * BrowserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrowserRepository extends \Doctrine\ORM\EntityRepository
{
}
