<?php

namespace MainBundle\Repository;

/**
 * UserEnvironmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEnvironmentRepository extends \Doctrine\ORM\EntityRepository
{
}
