<?php

namespace MainBundle\Repository;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * This tries to make one join query (in order to save two separate queries)
     * on the Visitor and UserEnvironment tables to get a single result.
     */
    public function findOneVisitorJoin($visitorId) {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT v, u FROM MainBundle:Visitor v
                JOIN v.userEnvironment u
                WHERE v.id = :id'
            )->setParameter('id', $visitorId);
        try {
            $visitor = $query->getSingleResult();
            return $visitor;
        } 
        catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    /*
     * This tries to make one join query (in order to save two separate queries)
     * on the Visitor and UserEnvironment tables to get a list of results.
     */
    public function findVisitorsJoin() {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT v, u FROM MainBundle:Visitor v
                JOIN v.userEnvironment u'
            );
        try {
            $visitors = $query->getArrayResult();
            return $visitors;
        } 
        catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
